spring.application.name=projecthub-backend

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true

security.jwt.secret-key=${SECRET-KEY}
security.jwt.expiration-time=${JWT-EXPIRATION-TIME}
security.jwt.refresh.expiration-time=${REFRESH-TOKEN-EXPIRATION-TIME}
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.example.projecthubbackend=DEBUG


